development:
  access_key_id: 'AKIAILUQ4OZEBWEEK3OA'
  secret_access_key: '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'
test:
  access_key_id: 'AKIAILUQ4OZEBWEEK3OA'
  secret_access_key: 'SZLLRKrOXP6uSjI+bTxXtia0xL0CDFx3PkUwQN6q'
production:
  access_key_id: your_access_key
  secret_access_key: your_secret_key

